### ISSUE TITLE
Removing spray-util dependency

### ISSUE THREAD

**Issue by barredijkstra** [CodeMettle/reactivemq#1]
Currently the project has 1 non-provided external dependency on "io.spray" %% "spray-util", mostly for some configuration wrappers.
When accepting the performance penalty of not using the sprayActorSystem configuration caching the change is quite straight-forward.

The removal of this dependency (which is only available at the moment for scala 2.10 and scala 2.11) will make the way clear for crossVersion building using scala 2.12, as well as making the dependency graph a little bit cleaner for users of the project.

I have a branch with a straight-forward implementation of a removed spray-util at;

https://github.com/barredijkstra/reactivemq/tree/no-spray

I have not run any performance tests on my own codebases where I use reactivemq, but given the usage I'd guess it's not too high in the grand scheme of things.

**Comment by codingismy11to7** [comment]
I'll look into this next week, thanks

**Comment by barredijkstra** [comment]
Closing in favor of #3
