### ISSUE TITLE
Support for scala 2.12

### ISSUE THREAD

**Issue by barredijkstra** [CodeMettle/reactivemq#2]
I was wondering if there are plans for providing a version for scala 2.12.

**Comment by barredijkstra** [comment]
I saw there was a release/1.0 branch where support for scala 2.10 was dropped; is this something that is still planned going forward or is scala 2.10 ideally supported? (for a quick poll; I don't run 2.10 anymore)

If 2.10 is still to be supported, I have a nasty hacked version supporting 2.10, 2.11 and 2.12 crossVersion builds with the latest available amq and akka versions for 2.10 and 2.11/2.12.
Not the nicest to maintain, but working in case 2.10 is still to be supported.

https://github.com/barredijkstra/reactivemq/tree/crossversion-hack

I will refrain from sending a pull request for this given the release/1.0 branch step of dropping scala 2.10 (which would remove the need for most of these hacks) and the hackiness of the solution ;-)

**Comment by codingismy11to7** [comment]
2.10 support is definitely dropped going forwards. I may have not merged 1.0 to master but it will be at some point, treat release/1.0 as the HEAD until I look into it. I'll look into this more next week, it's a holiday weekend.

**Comment by barredijkstra** [comment]
Thanks for the response, no hurries. Got a less hacky version based on the release/1.0 branch at https://github.com/barredijkstra/reactivemq/tree/1.0/scala-2.12 with support for scala 2.11 and 2.12. Also upgraded sbt, scalatest, akka and amq to latest version 
It's branched from release/1.0 and mergable; if you want a pull request, let me know when you had the time to look at it.

**Comment by barredijkstra** [comment]
Closing in favour of #3
